### ISSUE TITLE
C++ application built with librdkafka with GCC TSAN crashes when starting

### ISSUE THREAD

**Issue by thilinak** [confluentinc/librdkafka#4929]
### Discussed in https://github.com/confluentinc/librdkafka/discussions/4927

<div type='discussions-op-text'>

<sup>Originally posted by **thilinak** December  9, 2024</sup>
My application is built with librdkafka 1.6.0. It runs okay normally but when the application is built with TSAN flags (GCC) the application fails to start and crash stack is shown as below. Please help to resolve this. 

`
#0  0x00007ffff6d8409e in __tsan_func_entry () from /lib64/libtsan.so.0  
#1  0x00000000010aa9ae in KafkaClient::on_thread_start_trampoline(rd_kafka_s*, rd_kafka_thread_type_t, char const*, void*) ()  
#2  0x00007ffff55a26f3 in rd_kafka_interceptors_on_thread_start (rk=rk@entry=0x7b800003e000,  thread_type=thread_type@entry=RD_KAFKA_THREAD_MAIN) at rdkafka_interceptor.c:579  
#3  0x00007ffff550b27e in rd_kafka_thread_main (arg=0x7b800003e000) at rdkafka.c:1965  
#4  0x00007fffeeac32d2 in start_thread () from /lib64/libpthread.so.0  
#5  0x00007fffee71e8d3 in clone () from /lib64/libc.so.6  

`</div>

**Comment by hvilee** [comment]
Hi @emasab , I faced a similar issue, that librdkafka crash when build with GCC TSAN, backtrace is:
#0  0x00007f9b0ffc770b in ?? () from /usr/local/lib/clang/20/lib/x86_64-unknown-linux-gnu/libclang_rt.tsan.so
#1  0x00007f9b0ffc73a4 in ?? () from /usr/local/lib/clang/20/lib/x86_64-unknown-linux-gnu/libclang_rt.tsan.so
#2  0x00007f9b0ffc81ea in ?? () from /usr/local/lib/clang/20/lib/x86_64-unknown-linux-gnu/libclang_rt.tsan.so
#3  0x00007f9b0ff638e1 in __interceptor_realloc () from /usr/local/lib/clang/20/lib/x86_64-unknown-linux-gnu/libclang_rt.tsan.so
#4  0x00007f9b05e93645 in make_request (pid=11, fd=79) at ../sysdeps/unix/sysv/linux/check_pf.c:235
#5  __check_pf (seen_ipv4=seen_ipv4@entry=0x7f92b64ed8f6, seen_ipv6=seen_ipv6@entry=0x7f92b64ed8f7, in6ai=in6ai@entry=0x7f92b64ed908, in6ailen=in6ailen@entry=0x7f92b64ed910) at ../sysdeps/unix/sysv/linux/check_pf.c:341
#6  0x00007f9b05e44385 in __GI_getaddrinfo (name=<optimized out>, service=<optimized out>, hints=<optimized out>, pai=0x7f92b64ee048) at ../sysdeps/posix/getaddrinfo.c:2342
#7  0x00007f9b0ff6e0d2 in __interceptor_getaddrinfo () from /usr/local/lib/clang/20/lib/x86_64-unknown-linux-gnu/libclang_rt.tsan.so
#8  0x00007f9b03a6b518 in rd_getaddrinfo () from /usr/local/lib/librdkafka.so.1
#9  0x00007f9b03a97775 in rd_kafka_broker_thread_main () from /usr/local/lib/librdkafka.so.1
#10 0x00007f9b05dedde3 in start_thread (arg=<optimized out>) at pthread_create.c:441
#11 0x00007f9b05e75338 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
